// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbdnpkxtonqvvgzxvyyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZG5wa3h0b25xdnZnenh2eXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDE5MjYsImV4cCI6MjA3NDcxNzkyNn0.9xDjK_hW__K2Q6GqMErwSbcsYkmduzB-xfN9q-ywS-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});